server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  flyway:
    enabled: true
    locations: 'classpath:db/migration'
    placeholder-replacement: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: none

game:
  jwt:
    secret: ${JWT_SECRET}
  security:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS}
  round:
    multiplier: ${ROUND_WIN_MULTIPLIER}
    runner:
      fixedRate: ${ROUND_RUNNER_FIXED_RATE}
      initialDelay: ${ROUND_RUNNER_INITIAL_DELAY}
    duration: ${ROUND_DURATION_SECONDS}
    newRoundStartDelay: ${ROUND_NEW_ROUND_START_DELAY}
    betDelayLeewayNanos: ${ROUND_BET_DELAY_LEEWAY_NANOSECONDS}
    rollResultDelayNanos: ${ROUND_ROLL_RESULT_DELAY_NANOSECONDS}

logging:
  config: classpath:logback-consoleappender.xml
